[client]
showSidebarNavigation = false

[theme]
# Opcional: personaliza los colores de tu app
# primaryColor = "#00ff0dff"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"